modLoader="javafml"
loaderVersion="[47,)"
license="MIT Licence"

[[mods]]
modId="garnished_additions"
version="0.3.94"
displayName="Garnished Additions"
displayURL="https://modrinth.com/mod/garnished-additions"
credits=""
authors="Panda"
description='''
Create: Garnished Addon that adds new armour, tools, recipes, and foods!
'''

[[dependencies.garnished_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

